# .github/workflows/build.yml
name: Build and Release Executables

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ] # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true # Stop all jobs if one fails
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: s3tool-linux
            executable_name: s3tool-linux
            upx_command: |
              sudo apt-get update
              sudo apt-get install -y upx-ucl
          - os: windows-latest
            artifact_name: s3tool-windows
            executable_name: s3tool-win.exe
            upx_command: |
              choco install upx
              echo "UPX_DIR=C:\ProgramData\chocolatey\lib\upx\tools" >> $GITHUB_ENV

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install/Setup UPX
      if: matrix.upx_command != ''
      run: ${{ matrix.upx_command }}
      shell: bash

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --name ${{ matrix.executable_name }} \
                    --onefile \
                    --clean \
                    main.py
      shell: bash

    - name: Upload artifact for internal use/release job
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable_name }}
        if-no-files-found: error # Fail the workflow if the executable wasn't created

  release:
    name: Create Release and Upload Assets
    needs: build # Run after all build jobs complete
    runs-on: ubuntu-latest
    # Only run this job if a tag starting with 'v' was pushed
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write # Needed by softprops/action-gh-release to create releases

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded artifacts (for debugging)
        run: ls -R artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/s3tool-linux/s3tool-linux
            artifacts/s3tool-windows/s3tool-win.exe