# .github/workflows/build.yml
name: Build Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true # Stop all jobs if one fails
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: s3tool-linux
            executable_name: s3tool-linux
            upx_command: |
              sudo apt-get update
              sudo apt-get install -y upx-ucl
          - os: windows-latest
            artifact_name: s3tool-windows
            executable_name: s3tool-win.exe
            upx_command: |
              choco install upx
              echo "UPX_DIR=C:\ProgramData\chocolatey\lib\upx\tools" >> $GITHUB_ENV

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install/Setup UPX
      run: ${{ matrix.upx_command }}
      shell: bash

    - name: Build executable with PyInstaller and UPX
      run: |
        pyinstaller --name ${{ matrix.executable_name }} \
                    --onefile \
                    --clean \
                    main.py
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable_name }}
        if-no-files-found: error # Fail the workflow if the executable wasn't created